Listen 6789

# nThreads 4x
# # OR
nSelectLoops 4

<VirtualHost *:6789>
    DocumentRoot ./contents
    ServerName www.a.com
</VirtualHost>

<VirtualHost *:6789>
    DocumentRoot ./bontents
    ServerName www.b.com
</VirtualHost>